### ISSUE TITLE
feature: add browse-url utilities

### ISSUE THREAD

**Issue by Silex** [dgtized/github-clone.el#10]
Hello,

It'd be nice to be able to:

- go to repository in browser
- go to fork in browser
- go to pull request 

Here is a draft for it (not working anymore because of magit update):

``` elisp
;; Taken from http://endlessparentheses.com/easily-create-github-prs-from-magit.html?source=rss
(defun git/visit-pull-request-url ()
  "Visit the current branch's PR on Github."
  (interactive)
  (browse-url
   (format "https://github.com/%s/compare/%s"
     (replace-regexp-in-string
      "\\`.+github\\.com:\\(.+\\)\\.git\\'" "\\1"
      (magit-get "remote"
                 (magit-get-current-remote)
                 "url"))
     (magit-get-current-branch))))
```

Maybe the api could be:

- `M-x github-browse-repository`
- `M-x github-browse-fork`
- `M-x github-browse-pull-request`

**Comment by dgtized** [comment]
I don't think any of those require using the github API, and are just url construction. Currently I use https://github.com/osener/github-browse-file for related functionality, would that be more appropriate there?

**Comment by Silex** [comment]
Hum, yes that could work. Good idea, thanks.
