### ISSUE TITLE
Clone with https url when argument is given as 'user/repo'

### ISSUE THREAD

**Issue by timor** [dgtized/github-clone.el#24]
The default method seems to try to clone from the ssh url.  Is there a way to have it use https instead?

**Comment by dgtized** [comment]
Yep, that's exactly what the defcustom `github-clone-url-slot` specified in https://github.com/dgtized/github-clone.el/blob/master/github-clone.el#L47 does. If you would prefer to use https, customize the variable to use `:clone-url`.

Hope that helps, despite the long hiatus, sorry about that!
